# Generated by Django 3.2.5 on 2021-10-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table=None,
        ),
    ]
