# Generated by Django 3.2.5 on 2021-10-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_record_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, choices=[('国語', '国語'), ('数学', '数学'), ('英語', '英語'), ('理科', '理科'), ('社会', '社会')], max_length=10, null=True, verbose_name='教科'),
        ),
    ]
