# Generated by Django 3.2.5 on 2021-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(blank=True, choices=[('30', '30分'), ('40', '40分'), ('50', '50分'), ('60', '60分'), ('70', '70分'), ('80', '80分'), ('90', '90分'), ('100', '100分')], max_length=10, null=True, verbose_name='分'),
        ),
    ]
