# Generated by Django 3.2.5 on 2021-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='いつ'),
        ),
    ]
