# Generated by Django 3.2.5 on 2021-10-08 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0009_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='教科'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='分'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='国語')),
                ('math', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='数学')),
                ('english', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='英語')),
                ('science', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='理科')),
                ('social_studies', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='社会')),
                ('date', models.DateField(blank=True, null=True, verbose_name='いつまでに')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
